tiny_url_main_homepage:
    path:     /
    defaults: { _controller: TinyUrlMainBundle:Default:index }

tiny_url_main_redirect:
    path:    /{shortcode}
    defaults:  { _controller: TinyUrlMainBundle:Default:redirect}
    requirements:
      shortcode: "[A-Za-z0-9]{6}"

tiny_url_main_delete:
    path:    /{id}
    defaults:  { _controller: TinyUrlMainBundle:Default:delete}
    requirements:
      id: \d+