<?php

namespace TinyUrl\MainBundle\Repository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPopularLinks() {
        return $this->createQueryBuilder('l')
            ->orderBy('l.counter', 'DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->execute();
    }

    public function findLastAddedLinks() {
        return $this->createQueryBuilder('l')
            ->orderBy('l.createdAt', 'DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->execute();
    }
}
